An array can be reversed in many ways. This notebook contains all the possible ways to reverse a Numpy array.

# **Importing libraries**

In [1]:
import numpy as np

# **Techniques**

**Reversing a 1-D array**

In [8]:
#Slicing
def rev_arr_slicing(array):
  arr=array[::-1]
  return arr

#Using np.flip()
def rev_flip(array):
  arr=np.flip(array)
  return arr

#Using np.arange()
def rev_arange(array):
  arr=np.arange(len(array),0,-1)
  return arr



#Driver Code
arr=np.array([1,2,3,4,5,6])
result=rev_arr_slicing(arr)
print("Reversed using slicing: ",result)

result=rev_flip(arr)
print("Reversed using flip: ",result)

result=rev_arange(arr)
print("Reversed using arange: ",result)

Reversed using slicing:  [6 5 4 3 2 1]
Reversed using flip:  [6 5 4 3 2 1]
Reversed using arange:  [6 5 4 3 2 1]


**Rerversing a 2-D array**

In [13]:
#Using np.flip()
def rev_flip_vert(array):
  arr=np.flip(array,axis=0)
  return arr

def rev_hor_flip(array):
  arr=np.flip(array,axis=1)
  return arr

def rev_flip(array):
  arr=np.flip(array)
  return arr
#Driver Code
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

result=rev_flip_vert(array)
print("Reversed using Vertical flip: ", result)


result=rev_hor_flip(array)
print("Reversed using horizontal flip: ", result)

result=rev_flip(array)
print("Reversed using flip both axes: ", result)

Reversed using Vertical flip:  [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Reversed using horizontal flip:  [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Reversed using flip both axes:  [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
